# -*- coding: utf-8 -*-
"""Titanic - Machine Learning from Disaster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snTyzjdJPxnKSAXIwKMlgOo4iNo8PCPb
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

data = pd.read_csv('train.csv')

data.shape

data.isnull().sum()

data['Age'] = data['Age'].fillna(data['Age'].median())
data.isnull().sum()

cols = ['SibSp', 'Parch', 'Fare']

for col in cols:
  data[col].fillna(data[col].median(), inplace=True)

data.isnull().sum()

data ['Embarked'].fillna('U' , inplace = True)

data.isnull().sum()

dadata = data.drop(['SibSp', 'Parch', 'Age', 'Fare', 'Embarked'], axis=1) # Ensure all listed columns exist before dropping
data.isnull().sum()
data.head()

data['Sex'] = data['Sex'].map({'male' : 1 , 'female' : 2})
data.head()

data['Embarked'] = data['Embarked'].map({'S' : 1 , 'C' : 2 , 'Q' : 3 ,'U' : 4})
data.head()

x = data[['Sex'	,'Age'	,'SibSp',	'Parch',	'Fare'	,	'Embarked']]

x.head()

y= data['Survived']
y.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.75,random_state=0)

from sklearn.neighbors import   KNeighborsClassifier
k_nnModel = KNeighborsClassifier(n_neighbors=4)
k_nnModel.fit(x_train,y_train)
y_pred = k_nnModel.predict(x_test)

pd.DataFrame({"y_test" : y_test, "y_predict" : y_pred})

from sklearn.metrics import accuracy_score #Fixed typo in module name. Changed 'matrics' to 'metrics'
accuracy_score(y_test,y_pred)

from sklearn.linear_model import   LogisticRegression
line_Model = LogisticRegression()
line_Model.fit(x_train,y_train)
y_pred = line_Model.predict(x_test)

pd.DataFrame({"y_test" : y_test, "y_predict" : y_pred})

accuracy_score(y_test,y_pred)